Dodaj inforamcje odnosnie git config --global color.ui true
bikol/DINO202324 pull request #1
Opened 2023-11-08 10:23 UTC by MrJustice26

2023-11-15 22:37 UTC, bikol requested changes
proszę zmergować do aktualnej wersji kodu

2023-11-20 20:59 UTC, MrJustice26 commented
@bikol Zrobione

2023-11-21 16:57 UTC, bikol requested changes
potrzebny jest ponowny merge

2023-11-25 20:00 UTC, MrJustice26 commented
@bikol zrobione (proszę dać approve 🙏)

2023-11-29 08:28 UTC, merged