Add info about git bisect (start, bad, good, reset)
bikol/DINO202324 pull request #6
Opened 2023-11-15 08:19 UTC by Stanlee77

2023-11-15 22:38 UTC, bikol requested changes
proszę zmergować do aktualnej wersji kodu

2023-11-24 06:21 UTC, Stanlee77 commented
obecny branch jest aktualny z najnowszą wersją main

2023-11-29 08:27 UTC, bikol requested changes
proszę zrobić ponowny merge z obecnym stanem repozytorium

2023-12-06 08:03 UTC, Stanlee77 reviewed
mimo, że frament o komendzie git fetch "remote" "branch" jest autorstwa Maciej Kmieć, kod wyświetla się jako dodany przeze mnie, jednak został już zmergowany do main i nie był dodany przeze mnie

2024-01-15 11:42 UTC, Stanlee77 commented
still waiting for approve

2024-01-30 18:52 UTC, merged